export const GET_INITIAL_CONVERSION_START = 'GET_INITIAL_CONVERSION_START';
export const GET_INITIAL_CONVERSION_SUCCESS = 'GET_INITIAL_CONVERSION_SUCCESS';
export const GET_INITIAL_CONVERSION_FAILURE = 'GET_INITIAL_CONVERSION_FAILURE';

export const SWAP_CURRENCY_START = 'SWAP_CURRENCY_START';
export const SWAP_CURRENCY_SUCCESS = 'SWAP_CURRENCY_SUCCESS';
export const SWAP_CURRENCY_FAILURE = 'SWAP_CURRENCY_FAILURE';

export const CHANGE_BASE_CURRENCY_START = 'CHANGE_BASE_CURRENCY_START';
export const CHANGE_BASE_CURRENCY_SUCCESS = 'CHANGE_BASE_CURRENCY_SUCCESS';
export const CHANGE_BASE_CURRENCY_FAILURE = 'CHANGE_BASE_CURRENCY_FAILURE';

export const CHANGE_QUOTE_CURRENCY = 'CHANGE_QUOTE_CURRENCY';

export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const DID_TRY_AUTO_LOGIN = 'DID_TRY_AUTO_LOGIN';
